apiVersion: v1
kind: Service
spec:
  type: NodePort
  selector:
    app: {{gitops.name}}
  ports:
    - port: {{gitops.port}}
      targetPort: {{gitops.port}}
      nodePort: {{gitops.nodePort}}

metadata:
  namespace: {{gitops.namespace}}
  labels:
    app: {{gitops.name}}
  name: {{gitops.name}}
